### ISSUE TITLE
Thorlabs filter wheel get position fails.

### ISSUE THREAD

**Issue by iandobbie** [python-microscope/microscope#192]
Traceback below . I guess that the reply to "pos?" doesn't parse as an int. 

2021-02-26 15:33:22,563:ThorlabsFW102C (microscope.abc):ERROR:PID 6116: in get_setting(position):
Traceback (most recent call last):
  File "c:\microscope\microscope\abc.py", line 442, in get_setting
    return self._settings[name].get()
  File "c:\microscope\microscope\abc.py", line 156, in get
    value = self._get()
  File "c:\microscope\microscope\abc.py", line 1319, in get_position
    return self.position
  File "c:\microscope\microscope\abc.py", line 1293, in position
    return self._do_get_position()
  File "c:\microscope\microscope\filterwheels\thorlabs.py", line 83, in _do_get_position
    return int(self._send_command("pos?")) - 1
ValueError: invalid literal for int() with base 10: ''

**Comment by carandraug** [comment]
The reply seems to have been a empty string. Was there maybe a timeout?
