### ISSUE TITLE
picamera doesn't set ROI properly. 

### ISSUE THREAD

**Issue by iandobbie** [python-microscope/microscope#279]
The picamera module returns an error when you try to set the roi either interactively or via the settings menu. 

Traceback (most recent call last):
  File "C:\Users\idobbie1\src\cockpit\cockpit\gui\imageViewer\viewCanvas.py", line 811, in onMouse
    camera.setROI(roi)
  File "C:\Users\idobbie1\src\cockpit\cockpit\handlers\deviceHandler.py", line 123, in wrapper
    return f(self, *args, **kwargs)
  File "C:\Users\idobbie1\src\cockpit\cockpit\handlers\camera.py", line 231, in setROI
    return self.callbacks['setROI'](self.name, roi)
  File "C:\Users\idobbie1\src\cockpit\cockpit\devices\microscopeCamera.py", line 345, in setROI
    result = self._proxy.set_roi(roi)
  File "C:\Users\idobbie1\AppData\Local\Programs\Python\Python310\lib\site-packages\Pyro4\core.py", line 185, in __call__
    return self.__send(self.__name, args, kwargs)
  File "C:\Users\idobbie1\AppData\Local\Programs\Python\Python310\lib\site-packages\Pyro4\core.py", line 476, in _pyroInvoke
    raise data  # if you see this in your traceback, you should probably inspect the remote traceback as well
TypeError: _set_roi() missing 3 required positional arguments: 'top', 'width', and 'height'

I suspect that the picamera modules isn't properly dealing roi objects. I will investigate.

**Comment by iandobbie** [comment]
As suspected the code was expecting 4 parameters not a named ROI() tuple. Fixed
